apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: postgres-tls
  commonName: postgres
  dnsNames:
    - {{ .Release.Name }}-postgresql
    - {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: demo-ca
    kind: ClusterIssuer